version: '2.1'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql
      - ./backup:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@dv202305"
    networks:
      - app_network
    user: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mssql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mssql-data: